# Docker Compose com Scheduler Separado
# Para usar: docker-compose -f docker-compose.scheduler.yml up

services:
  # API Flask (sem scheduler)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      # Flask configuration
      - FLASK_ENV=development
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5001
      - FLASK_DEBUG=false
      
      # Database configuration
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=paridaderisco
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      
      # General Python configuration
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=utf-8
      
      # Modo de execução
      - RUN_MODE=api-only
      - SCHEDULER_ENABLED=false
      
    restart: unless-stopped
    ports:
      - "5002:5001"
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Scheduler separado
  scheduler:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      # Database configuration
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=paridaderisco
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      
      # General Python configuration
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=utf-8
      - TZ=America/Sao_Paulo
      
      # Modo de execução
      - RUN_MODE=scheduler-only
      
      # Scheduler configuration
      - SCHEDULER_ENABLED=true
      - SCHEDULER_TIMEZONE=America/Sao_Paulo
      - SCHEDULER_MAX_WORKERS=3
      - SCHEDULER_LOG_LEVEL=INFO
      
      # Job configuration
      - SCHEDULER_YAHOO_ENABLED=true
      - SCHEDULER_YAHOO_HOUR=8
      - SCHEDULER_YAHOO_MINUTE=0
      - SCHEDULER_RTD_COMERCIAL_ENABLED=true
      - SCHEDULER_RTD_COMERCIAL_INTERVAL=30
      - SCHEDULER_RTD_NOTURNO_ENABLED=true
      - SCHEDULER_SAUDE_ENABLED=true
      - SCHEDULER_SAUDE_INTERVAL=120
      
    restart: unless-stopped
    depends_on:
      - postgres
      - backend
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://backend:5001/api/status')"]
      interval: 60s
      timeout: 15s
      retries: 3
      start_period: 120s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=http://localhost:5002/api
    ports:
      - "8080:3000"

  # PostgreSQL local
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=paridaderisco
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migration/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: